- name: Kubernetes hello world
  hosts: localhost
  tasks:
    - name: Create a test pod
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Pod
          name: test-pod
          namespace: default
          spec:
            containers:
            - name: test-pod
              image: registry.redhat.io/rhel7:latest
              imagePullPolicy: IfNotPresent
              args:
              - sleep
              - "2000"
